/* AqylJol: local demonstration. No live transport data or external AI. */
'use strict';
const ICONS={home:'M3 10 12 3l9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z',map:'m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2Zm6-2v16m6-14v16',bus:'M5 17h14V6c0-2-14-2-14 0Zm0-7h14M7 17v3m10-3v3M8 14h.01M16 14h.01',chat:'M21 11a9 9 0 0 1-9 9H4l-2 2V11a9 9 0 0 1 19 0ZM7 11h.01M12 11h.01M17 11h.01',heart:'M20 5c-3-3-7-1-8 1-1-2-5-4-8-1-4 4 0 9 8 15 8-6 12-11 8-15Z',pin:'M19 9c0 5-7 12-7 12S5 14 5 9a7 7 0 0 1 14 0ZM14 9a2 2 0 1 1-4 0 2 2 0 0 1 4 0',arrow:'M5 12h14m-6-6 6 6-6 6',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z',target:'M21 12h-3M6 12H3m9-9v3m0 12v3M18 12a6 6 0 1 1-12 0 6 6 0 0 1 12 0',sun:'M12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10ZM12 2v2M12 20v2M4.2 4.2l1.4 1.4M18.4 18.4l1.4 1.4M2 12h2M20 12h2M4.2 19.8l1.4-1.4M18.4 5.6l1.4-1.4',moon:'M20 14.5A8.5 8.5 0 1 1 9.5 4a7 7 0 0 0 10.5 10.5Z',gear:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM12 2v3M12 19v3M4.2 4.2l2.1 2.1M17.7 17.7l2.1 2.1M2 12h3M19 12h3M4.2 19.8l2.1-2.1M17.7 6.3l2.1-2.1'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${ICONS[n]||ICONS.bus}"/></svg>`;
// Scatters demo stop markers around a city center on varying angles/radii, so different subsets/orders of stops read as distinct routes.
// The stop NAMES below are real, well-known places in each city; only their exact pin position and the bus service itself are approximated for the demo.
function demoPoints(center,n){const[la,lo]=center;const latCorr=Math.cos(la*Math.PI/180)||1;return Array.from({length:n},(_,i)=>{const angle=(360/n*i+18)*Math.PI/180;const radius=.009+.014*((i*5)%n)/(n-1);return[+(la+radius*Math.sin(angle)).toFixed(4),+(lo+radius*Math.cos(angle)/latCorr).toFixed(4)]})}
function mkCity(name,center,stops){return{name,center,points:demoPoints(center,stops.length),stops}}
// Coordinates are real city centers (approximate); stop names are real local landmarks. The bus numbers, fleet, seats and timing are fictional.
const CITIES={
 atyrau:mkCity('Атырау',[47.106,51.914],['Площадь Исатая и Махамбета','Парк Пушкина','АГУ им. Х. Досмухамедова','Атырауская мечеть','Ж/д вокзал Атырау','Городская больница','Жилгородок','Набережная реки Урал']),
 astana:mkCity('Астана',[51.131,71.424],['Площадь Независимости','Центральный парк','Nazarbayev University','Байтерек','Вокзал Нурлы Жол','Городская больница №1','Левый берег','Хан Шатыр']),
 almaty:mkCity('Алматы',[43.246,76.925],['Площадь Республики','Парк 28 панфиловцев','КазНУ им. аль-Фараби','Кок-Тобе','Вокзал Алматы-2','Городская клиническая больница','Микрорайон Самал','Зелёный базар']),
 shymkent:mkCity('Шымкент',[42.317,69.586],['Площадь Ордабасы','Парк Независимости','ЮКУ им. М. Ауэзова','Шымкентский цирк','Ж/д вокзал Шымкент','Городская больница №1','Микрорайон Нурсат','Центральный рынок']),
 karaganda:mkCity('Караганда',[49.807,73.087],['Площадь Независимости','Центральный парк отдыха','КарГУ им. Е.А. Букетова','Дворец культуры горняков','Ж/д вокзал Караганда','Областная больница','Посёлок Пришахтинск','Стадион «Шахтёр»']),
 aktobe:mkCity('Актобе',[50.283,57.167],['Площадь Астана','Парк Победы','АРУ им. К. Жубанова','Дом дружбы','Ж/д вокзал Актобе','Городская больница','Микрорайон Батыс','Центральный рынок']),
 taraz:mkCity('Тараз',[42.9,71.365],['Площадь Достык','Парк Абая','ТарГУ им. М.Х. Дулати','Набережная реки Талас','Ж/д вокзал Тараз','Городская больница','Микрорайон Юго-Восток','Центральный базар']),
 pavlodar:mkCity('Павлодар',[52.287,76.957],['Центральная площадь','Парк культуры и отдыха','ПГУ им. С. Торайгырова','Набережная Иртыша','Ж/д вокзал Павлодар','Городская больница','Микрорайон Восточный','Центральный рынок']),
 oskemen:mkCity('Усть-Каменогорск',[49.949,82.628],['Площадь им. Абая','Парк Жастар','ВКТУ им. Д. Серикбаева','Стрелка','Ж/д вокзал Оскемен','Городская больница','Согра','Набережная Иртыша']),
 semey:mkCity('Семей',[50.411,80.227],['Площадь Абая','Парк им. Абая','Мед. университет Семей','Вантовый мост через Иртыш','Ж/д вокзал Семей','Городская больница','Микрорайон Восточный','Центральный рынок']),
 kostanay:mkCity('Костанай',[53.214,63.629],['Центральная площадь','Парк им. Шевченко','КРУ им. А. Байтурсынова','Набережная реки Тобол','Ж/д вокзал Костанай','Городская больница','Микрорайон Центральный','Центральный рынок']),
 petropavlovsk:mkCity('Петропавловск',[54.875,69.146],['Центральная площадь','Парк Победы','СКУ им. М. Козыбаева','Набережная реки Ишим','Ж/д вокзал Петропавловск','Городская больница','Рабочий посёлок','Центральный рынок']),
 uralsk:mkCity('Уральск',[51.233,51.367],['Центральная площадь','Парк им. Гагарина','ЗКАТУ им. Жангир хана','Набережная реки Урал','Ж/д вокзал Уральск','Городская больница','Зачаганск','Центральный рынок']),
 kyzylorda:mkCity('Кызылорда',[44.848,65.502],['Центральная площадь','Парк им. Гагарина','Университет им. Коркыт Ата','Набережная реки Сырдарья','Ж/д вокзал Кызылорда','Городская больница','Тасбогет','Центральный рынок']),
 aktau:mkCity('Актау',[43.65,51.2],['Микрорайон 1','Парк им. Абая','Каспийский университет им. Ш. Есенова','Набережная Каспийского моря','Вокзал Мангышлак','Городская больница','Микрорайон 5','Центральный рынок']),
 turkistan:mkCity('Туркестан',[43.297,68.251],['Мавзолей Ходжи Ахмеда Ясави','Парк Независимости','Университет им. Ясави','Мавзолей Рабии Султан-бегим','Ж/д вокзал Туркестан','Городская больница','Микрорайон Нурлы Жол','Центральный рынок'])
};
// eta: минуты до прибытия · walk: минуты пешком до посадки · transfers: число пересадок — весь автобусный сервис ниже вымышленный.
// order: индексы остановок выбранного города — у каждого автобуса свой набор и порядок, а не перестановка одних и тех же пяти.
const BUSES=[
 {id:'14',name:'Через центр',seats:18,capacity:30,eta:4,walk:3,transfers:0,color:'#006d70',order:[0,2,3,5]},
 {id:'30',name:'Городская линия',seats:25,capacity:30,eta:7,walk:6,transfers:0,color:'#6150a5',order:[7,6,3,1,0]},
 {id:'12',name:'Короткий маршрут',seats:3,capacity:24,eta:2,walk:8,transfers:1,color:'#bb6b32',order:[1,3,4]},
 {id:'5',name:'Университетская',seats:12,capacity:26,eta:6,walk:5,transfers:0,color:'#2f8f5b',order:[0,4,3,2]},
 {id:'21',name:'Вокзальная',seats:9,capacity:28,eta:9,walk:4,transfers:1,color:'#c23c6b',order:[6,5,3,0]},
 {id:'8',name:'Больничная',seats:20,capacity:30,eta:5,walk:2,transfers:0,color:'#1f7a99',order:[5,4,2,7]},
 {id:'45',name:'Экспресс',seats:6,capacity:20,eta:3,walk:7,transfers:0,color:'#8a4fd1',order:[0,3,6]},
 {id:'17',name:'Кольцевая',seats:15,capacity:32,eta:11,walk:5,transfers:0,color:'#b3781f',order:[0,1,2,3,4,5,6,7,0]}
];
// --- Индекс комфорта: сводит время ожидания, свободные места, пересадки и путь пешком в одну оценку 0–10.
function comfortScore(b){const seatRatio=b.seats/b.capacity;const etaScore=Math.max(0,1-b.eta/15);const walkScore=Math.max(0,1-b.walk/15);const transferScore=b.transfers===0?1:b.transfers===1?.5:.2;return Math.round((seatRatio*.4+etaScore*.3+walkScore*.15+transferScore*.15)*100)/10}
function comfortLabel(score){return score>=8?'Отлично':score>=6?'Хорошо':score>=4?'Средне':'Напряжённо'}
function comfortTier(score){return score>=8?'great':score>=6?'good':score>=4?'mid':'low'}
// --- Прогноз заполненности: если свободных мест меньше 20%, предупреждаем и предлагаем более комфортный автобус.
function crowdForecast(b){const ratio=b.seats/b.capacity;return ratio<=.2?{soon:true,minutes:Math.max(1,Math.round(b.eta/2))}:{soon:false}}
function bestAlternative(exclude){return BUSES.filter(b=>b.id!==exclude.id).reduce((best,b)=>comfortScore(b)>comfortScore(best)?b:best)}
// --- Предупреждения о задержках и переполненности: раз в ~22с слегка меняем демо-данные одного автобуса и уведомляем.
function simulateDisruptions(onChange){setInterval(()=>{if(document.hidden)return;const b=BUSES[Math.floor(Math.random()*BUSES.length)];if(Math.random()<.5){b.eta=Math.min(18,b.eta+1+Math.floor(Math.random()*3));toast(`Автобус ${b.id} задерживается, новый прогноз — ${b.eta} мин`)}else{b.seats=Math.max(0,b.seats-1-Math.floor(Math.random()*2));if(b.seats/b.capacity<=.2)toast(`Автобус ${b.id} почти заполнен — ${b.seats} мест из ${b.capacity}`)}onChange&&onChange()},22000)}
function routeLineMotif(){const cols=BUSES.slice(0,3).map(b=>b.color);return `<svg class="hero-line" viewBox="0 0 420 220" aria-hidden="true" focusable="false"><path d="M-10 165 C 90 55, 210 205, 430 70" fill="none" stroke="${cols[0]}" stroke-width="3" stroke-linecap="round" stroke-dasharray="1 15"/><path d="M-10 90 C 120 180, 260 10, 430 150" fill="none" stroke="${cols[1]}" stroke-width="3" stroke-linecap="round" stroke-dasharray="1 15"/><circle cx="96" cy="120" r="6" fill="${cols[0]}"/><circle cx="248" cy="60" r="6" fill="${cols[1]}"/><circle cx="340" cy="140" r="6" fill="${cols[2]}"/></svg>`}
const $=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let memory={},storageOK=true;
try{localStorage.setItem('aq-test','1');localStorage.removeItem('aq-test')}catch{storageOK=false}
function read(key,fallback){try{const v=storageOK?localStorage.getItem('aq-'+key):memory[key];return v?JSON.parse(v):fallback}catch{return fallback}}
function save(key,value){memory[key]=JSON.stringify(value);try{if(storageOK)localStorage.setItem('aq-'+key,memory[key])}catch{storageOK=false;toast('Хранилище недоступно: изменения останутся только на этой странице.')}}
// --- Тёмная/светлая тема: применяется сразу на каждой странице и хранится в настройках устройства.
function applyTheme(pref){const dark=pref==='dark'||(pref==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.setAttribute('data-theme',dark?'dark':'light');const mc=document.querySelector('meta[name="theme-color"]');if(mc)mc.setAttribute('content',dark?'#04181a':'#006d70')}
let theme=read('theme','system');if(!['light','dark','system'].includes(theme))theme='system';
applyTheme(theme);
if(matchMedia){matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if(theme==='system')applyTheme('system')})}
const params=new URLSearchParams(location.search);
let city=params.get('city')||read('city','atyrau');if(!CITIES[city])city='atyrau';save('city',city);
const page=document.body.dataset.page||'home';
let favorites=read('favorites',[]);if(!Array.isArray(favorites))favorites=[];
let requests=read('requests',[]);if(!Array.isArray(requests))requests=[];
const url=(file,extra={})=>`${file}?${new URLSearchParams({city,...extra})}`;
const route=id=>BUSES.find(b=>b.id===String(id));
const key=b=>`${city}:${b.id}`;
const favored=b=>favorites.includes(key(b));
let toastTimer;
function toast(text){$('#toast').textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').textContent='',3500)}
function toggleFavorite(id){const b=route(id);if(!b)return;const k=key(b);favorites=favorites.includes(k)?favorites.filter(x=>x!==k):[...favorites,k];save('favorites',favorites);document.querySelectorAll(`[data-favorite="${id}"]`).forEach(el=>{el.classList.toggle('saved',favored(b));el.setAttribute('aria-pressed',String(favored(b)));el.setAttribute('aria-label',favored(b)?'Убрать из избранного':'В избранное');el.textContent=favored(b)?'★':'☆'});toast(favored(b)?'Маршрут сохранён на этом устройстве':'Маршрут убран из избранного');if(page==='trips')renderFavorites()}
const nav=[['home','index.html','home','Главная'],['map','map.html','map','Карта'],['routes','routes.html','bus','Маршруты'],['assistant','assistant.html','chat','Помощник'],['trips','trips.html','heart','Поездки'],['about','about.html','spark','О нас'],['settings','settings.html','gear','Настройки']];
$('#header').innerHTML=`<a class="brand" href="${url('index.html')}"><span class="brandmark">A</span><span>Aqyl<b>Jol</b></span></a><label class="citylabel">${icon('pin')}<select id="city" aria-label="Выбрать город">${Object.entries(CITIES).map(([id,c])=>`<option value="${id}" ${id===city?'selected':''}>${c.name}</option>`).join('')}</select></label>`;
$('#nav').innerHTML=nav.map(([id,file,i,label])=>`<a href="${url(file)}" ${id===page?'class="active" aria-current="page"':''}>${icon(i)}<span>${label}</span></a>`).join('');
$('#city').addEventListener('change',e=>{save('city',e.target.value);location.href=`${nav.find(x=>x[0]===page)[1]}?city=${e.target.value}`});
if(!storageOK){const w=document.createElement('div');w.className='storage-warning';w.textContent='Браузер запретил сохранение. Избранное и заявки не сохранятся после закрытия страницы.';$('#header').after(w)}
document.addEventListener('click',e=>{const f=e.target.closest('[data-favorite]');if(f)toggleFavorite(f.dataset.favorite)});
const heading=(title,sub='')=>`<div class="pageheading"><div><h1>${title}</h1>${sub?`<p class="city-caption">${sub}</p>`:''}</div></div>`;
function busCard(b,onMap=false){const score=comfortScore(b);const crowd=crowdForecast(b);const alt=crowd.soon?bestAlternative(b):null;return `<article class="buscard" style="--accent:${b.color}"><div class="bushead"><div class="busidentity"><span class="route-number">${b.id}</span><div><div class="route-name">${b.name}</div><div class="route-stats"><span>${b.order.length} остановок</span><span>${b.walk} мин пешком</span><span>${b.transfers?b.transfers+' пересадка':'без пересадок'}</span></div></div></div><span class="eta">${b.eta}<small>мин</small></span></div><div class="comfortrow"><span class="comfort comfort-${comfortTier(score)}">${icon('spark')} ${score.toFixed(1)} комфорт — ${comfortLabel(score)}</span></div><div class="seatrow"><span>Свободных сидений</span><span class="seatlabel ${b.seats<5?'busy':''}">${b.seats} из ${b.capacity}</span></div><div class="seatbar" title="Доля занятых сидений"><span style="width:${100-b.seats/b.capacity*100}%;${b.seats<5?'background:var(--coral)':''}"></span></div>${crowd.soon?`<div class="crowd-warn">${icon('bus')} Скоро будет переполнен (~${crowd.minutes} мин) — попробуй №${alt.id} «${alt.name}»</div>`:''}<div class="actions">${onMap?`<button class="primary" data-select="${b.id}">Показать автобус ${icon('target')}</button>`:`<a class="primary" href="${url('map.html',{bus:b.id})}">На карте ${icon('arrow')}</a>`}<button class="star ${favored(b)?'saved':''}" data-favorite="${b.id}" aria-label="${favored(b)?'Убрать из избранного':'В избранное'}" aria-pressed="${favored(b)}">${favored(b)?'★':'☆'}</button></div></article>`}
function home(){
 const freest=BUSES.reduce((a,b)=>b.seats>a.seats?b:a);
 const freestCard=b=>`<span class="tag">Свободнее всего</span><h2>Автобус №${b.id}</h2><p class="muted">Сейчас здесь больше всего свободных мест.</p><div class="mini-stat"><span>Свободных сидений</span><strong>${b.seats} / ${b.capacity}</strong></div><a class="linkbutton" href="${url('map.html',{bus:b.id})}">Посмотреть на карте ${icon('arrow')}</a>`;
 $('#app').innerHTML=heading('Куда поедем?')+`<div class="twocol"><section class="hero">${routeLineMotif()}<span class="hero-tag">Твой город — ближе</span><h1>Меньше ожидания.<br>Больше свободных мест.</h1><p>Посмотри движение автобусов на карте и выбери поездку, в которой тебе комфортно.</p><a class="primary" href="${url('map.html')}">Открыть карту ${icon('arrow')}</a></section><section><div class="quickgrid"><a class="quick" href="${url('routes.html')}">${icon('bus')}Маршруты</a><a class="quick" href="${url('assistant.html')}">${icon('spark')}Помощник</a><a class="quick" href="${url('trips.html')}">${icon('heart')}Избранное</a></div><div id="freest-card" class="card">${freestCard(freest)}</div></section></div><section class="section"><div class="sectiontitle"><h2>Выбери свою поездку</h2><a class="linkbutton" href="${url('routes.html')}">Все маршруты</a></div><div id="home-routes" class="routesgrid">${BUSES.slice(0,3).map(b=>busCard(b)).join('')}</div></section><p class="footnote">Доступно ${Object.keys(CITIES).length} городов Казахстана. Избранное и заявки сохраняются только в этом браузере.</p>`;
 simulateDisruptions(()=>{$('#home-routes').innerHTML=BUSES.slice(0,3).map(b=>busCard(b)).join('');const f=BUSES.reduce((a,b)=>b.seats>a.seats?b:a);$('#freest-card').innerHTML=freestCard(f)});
}
const SORTS={comfort:{label:'Комфортнее',fn:(a,b)=>comfortScore(b)-comfortScore(a)},fast:{label:'Быстрее',fn:(a,b)=>a.eta-b.eta},free:{label:'Свободнее',fn:(a,b)=>b.seats-a.seats},walk:{label:'Меньше пешком',fn:(a,b)=>a.walk-b.walk}};
function routes(){
 $('#app').innerHTML=heading('Маршруты','Найди автобус по номеру или названию')+`<input id="search" class="search" placeholder="Номер или название маршрута" aria-label="Поиск маршрута"><div class="filters" aria-label="Фильтры"><button class="chip active" data-filter="all" aria-pressed="true">Все автобусы</button><button class="chip" data-filter="free" aria-pressed="false">Есть свободные места</button><button class="chip" data-filter="fav" aria-pressed="false">Избранное</button></div><p class="sortlabel muted">Выбрать по принципу:</p><div class="filters" aria-label="Сортировка">${Object.entries(SORTS).map(([id,s])=>`<button class="chip ${id==='comfort'?'active':''}" data-sort="${id}" aria-pressed="${id==='comfort'}">${s.label}</button>`).join('')}</div><div id="route-results" class="routesgrid"></div>`;
 let filter='all',sort='comfort';function update(){const q=$('#search').value.toLowerCase().trim();const found=BUSES.filter(b=>(b.id+' '+b.name).toLowerCase().includes(q)&&(filter!=='free'||b.seats>=10)&&(filter!=='fav'||favored(b))).sort(SORTS[sort].fn);$('#route-results').innerHTML=found.length?found.map(b=>busCard(b)).join(''):'<div class="card empty">Маршруты не найдены. Измени поиск или фильтр.</div>'}
 $('#search').addEventListener('input',update);document.querySelectorAll('[data-filter]').forEach(el=>el.addEventListener('click',()=>{filter=el.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===el);x.setAttribute('aria-pressed',String(x===el))});update()}));document.querySelectorAll('[data-sort]').forEach(el=>el.addEventListener('click',()=>{sort=el.dataset.sort;document.querySelectorAll('[data-sort]').forEach(x=>{x.classList.toggle('active',x===el);x.setAttribute('aria-pressed',String(x===el))});update()}));document.addEventListener('click',e=>{if(e.target.closest('[data-favorite]')&&filter==='fav')update()});update();simulateDisruptions(update);
}
function legacyMapPage(){
 $('#app').innerHTML=heading('Город в движении')+`<div class="mapgrid"><section><div class="mapwrap"><div id="map" class="map" aria-label="Карта ${CITIES[city].name}"></div></div><div class="maptools"><button id="center-map" class="secondary">${icon('target')} Весь маршрут</button><button id="pause" class="secondary" aria-pressed="false">Приостановить</button></div><p id="map-status" class="mapstatus" role="status">Загружаем карту из интернета…</p><p class="footnote">Линии показывают маршрут между остановками. Остановки — реальные места города; автобусы, их число и движение на линии — вымышленные, для примера.</p></section><section><div id="selected-bus"></div><div class="card"><h2>Остановки</h2><ol id="stops" class="stops"></ol></div><div class="filters">${BUSES.map(b=>`<button class="chip" data-select="${b.id}" aria-pressed="false">Автобус ${b.id}</button>`).join('')}</div></section></div>`;
 let selected=route(params.get('bus'))||BUSES[0];let map,layer,stopLayer,paused=false;const markers=new Map(),progress=new Map(BUSES.map((b,i)=>[b.id,(.13+i*.24)%1]));
 function select(id){selected=route(id)||selected;$('#selected-bus').innerHTML=busCard(selected,true);$('#stops').innerHTML=selected.order.map(i=>`<li>${CITIES[city].stops[i]}</li>`).join('');document.querySelectorAll('.chip[data-select]').forEach(el=>{el.classList.toggle('active',el.dataset.select===selected.id);el.setAttribute('aria-pressed',String(el.dataset.select===selected.id))});const next=new URL(location.href);next.searchParams.set('bus',selected.id);history.replaceState(null,'',next);if(!map)return;if(layer)map.removeLayer(layer);if(stopLayer)map.removeLayer(stopLayer);const pts=selected.order.map(i=>CITIES[city].points[i]);layer=L.polyline(pts,{color:selected.color,weight:5,opacity:.7,dashArray:'8 7'}).addTo(map);stopLayer=L.layerGroup(selected.order.map(i=>L.marker(CITIES[city].points[i],{icon:L.divIcon({className:'',html:'<div class="stopdot"></div>',iconSize:[14,14]}),title:CITIES[city].stops[i]}).bindPopup(CITIES[city].stops[i]))).addTo(map);markers.forEach((m,id)=>m.setIcon(markerIcon(route(id),id===selected.id)));map.fitBounds(layer.getBounds(),{padding:[45,45]})}
 function markerIcon(b,chosen){return L.divIcon({className:'',html:`<div class="mapmarker ${chosen?'chosen':''}">${icon('bus')}${b.id}</div>`,iconSize:[58,38],iconAnchor:[29,19]})}
 function position(b,t){const pts=b.order.map(i=>CITIES[city].points[i]);const ping=t<.5?t*2:(1-t)*2;const p=Math.min(ping*(pts.length-1),pts.length-1-.000001);const i=Math.floor(p),f=p-i;return [pts[i][0]+(pts[i+1][0]-pts[i][0])*f,pts[i][1]+(pts[i+1][1]-pts[i][1])*f]}
 select(selected.id);document.addEventListener('click',e=>{const b=e.target.closest('[data-select]');if(b)select(b.dataset.select)});
 simulateDisruptions(()=>select(selected.id));
 if(!window.L){$('#map').innerHTML='<div class="error">Карта не загрузилась. Проверь интернет и обнови страницу. Список автобусов остаётся доступен.</div>';$('#map-status').textContent='Нет подключения к библиотеке карты.';$('#center-map').disabled=true;$('#pause').disabled=true;return}
 map=L.map('map',{scrollWheelZoom:true}).setView(CITIES[city].center,13);
 const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);
 let tileError=false;tiles.on('tileerror',()=>{tileError=true;$('#map-status').textContent='Часть карты не загрузилась. Проверь интернет — список автобусов всё равно доступен.'});tiles.on('load',()=>{if(!tileError)$('#map-status').textContent='Карта OpenStreetMap'});
 BUSES.forEach(b=>{const m=L.marker(position(b,progress.get(b.id)),{icon:markerIcon(b,b.id===selected.id),title:`Демо-автобус ${b.id}`,zIndexOffset:500}).addTo(map).on('click',()=>select(b.id));markers.set(b.id,m)});select(selected.id);
 $('#center-map').addEventListener('click',()=>map.fitBounds(layer.getBounds(),{padding:[45,45]}));$('#pause').addEventListener('click',()=>{paused=!paused;$('#pause').textContent=paused?'Продолжить':'Приостановить';$('#pause').setAttribute('aria-pressed',String(paused))});
 setInterval(()=>{if(paused||document.hidden)return;BUSES.forEach(b=>{progress.set(b.id,(progress.get(b.id)+.0018)%1);markers.get(b.id).setLatLng(position(b,progress.get(b.id)))})},650);
}
// Bot copy in Russian and Kazakh. Kazakh strings are a first draft for the demo and should be checked by a native speaker before real use.
const BOT_T={
 ru:{title:'Твой помощник',subtitle:'Помощник по маршрутам',placeholder:'Спроси про автобус или напиши «к 8:00»…',q1:'Где свободнее?',q2:'Что приедет раньше?',q3:'Нужно успеть к 8:00',
  greet:c=>`Привет! Мы в городе ${c}. Найдём более свободный и комфортный автобус?`,
  info:b=>`В городе ${CITIES[city].name}: автобус №${b.id} «${b.name}». Ожидание — ${b.eta} мин, пешком до остановки — ${b.walk} мин, свободных мест — ${b.seats} из ${b.capacity}. Индекс комфорта — ${comfortScore(b).toFixed(1)} (${comfortLabel(comfortScore(b))}).`,
  deadlineFit:(mins,b)=>`Чтобы успеть примерно за ${mins} мин, лучше всего подходит автобус №${b.id} «${b.name}» — индекс комфорта ${comfortScore(b).toFixed(1)}.`,
  deadlineMiss:'Впритык ни один автобус не успевает — вот самый быстрый вариант, но стоит выйти пораньше:',
  fallback:()=>`Могу сравнить свободные места, время прибытия и индекс комфорта автобусов ${BUSES.map(b=>b.id).join(', ')}. Напиши «к скольки» тебе надо, и я подберу вариант.`,
  footnote:'Помощник понимает «к 8:00», сравнивает автобусы по индексу комфорта и открывает их на карте.'},
 kz:{title:'Сенің көмекшің',subtitle:'Маршруттар бойынша көмекші',placeholder:'Автобус туралы сұра немесе «сағат 8:00-ге» деп жаз…',q1:'Қай жерде бос орын көп?',q2:'Қайсысы ертерек келеді?',q3:'Сағат 8:00-ге үлгеруім керек',
  greet:c=>`Сәлем! Біз ${c} қаласындамыз. Бос орны көбірек, ыңғайлырақ автобус іздейік пе?`,
  info:b=>`${CITIES[city].name} қаласында: №${b.id} автобус, «${b.name}». Күту уақыты — ${b.eta} мин, аялдамаға дейін жаяу — ${b.walk} мин, бос орын — ${b.capacity} орыннан ${b.seats}. Ыңғайлылық индексі — ${comfortScore(b).toFixed(1)} (${comfortLabel(comfortScore(b))}).`,
  deadlineFit:(mins,b)=>`Шамамен ${mins} минутта үлгеру үшін №${b.id} «${b.name}» автобусы ең қолайлысы — ыңғайлылық индексі ${comfortScore(b).toFixed(1)}.`,
  deadlineMiss:'Бірде-бір автобус дәл үлгермейді — міне ең жылдам нұсқа, бірақ ертерек шыққан жөн:',
  fallback:()=>`${BUSES.map(b=>b.id).join(', ')} автобустарының бос орнын, келу уақытын және ыңғайлылық индексін салыстыра аламын. «Сағат нешеге» керек екенін жаз, нұсқа таңдап беремін.`,
  footnote:'Көмекші «сағат 8:00-ге» деген сияқты уақытты түсінеді, автобустарды ыңғайлылық индексі бойынша салыстырады және картада көрсетеді.'}
};
function parseDeadline(text){const m=text.match(/(?:к|до|на|сағат)\s*(\d{1,2})(?::(\d{2}))?/i);if(!m)return null;const now=new Date();const target=new Date(now);target.setHours(+m[1],m[2]?+m[2]:0,0,0);if(target<=now)target.setDate(target.getDate()+1);return Math.round((target-now)/60000)}
function assistant(){
 let lang=read('lang','ru');if(!['ru','kz'].includes(lang))lang='ru';
 function t(){return BOT_T[lang]}
 $('#app').innerHTML=`<div class="assistantpage">${heading(lang==='ru'?'Спросить Aqyl':'Aqyl-дан сұрау')}<section class="card"><div class="chatintro"><span class="botavatar">${icon('spark')}</span><div><h2 style="margin:0">${t().title}</h2><span class="muted">${t().subtitle}</span></div></div><div class="filters" aria-label="Язык / Тіл"><button class="chip ${lang==='ru'?'active':''}" data-lang="ru" aria-pressed="${lang==='ru'}">Русский</button><button class="chip ${lang==='kz'?'active':''}" data-lang="kz" aria-pressed="${lang==='kz'}">Қазақша</button></div><div id="messages" class="messages" role="log" aria-live="polite" aria-label="Сообщения помощника"></div><div class="filters"><button class="chip" data-ask="${t().q1}">${t().q1}</button><button class="chip" data-ask="${t().q2}">${t().q2}</button><button class="chip" data-ask="${t().q3}">${t().q3}</button></div><form id="chat-form" class="chat-form"><input class="search" id="question" maxlength="300" required placeholder="${t().placeholder}" aria-label="Вопрос помощнику" autocomplete="off"><button class="primary" aria-label="Отправить вопрос">${icon('arrow')}</button></form></section><p class="footnote">${t().footnote}</p></div>`;
 function message(text,user=false,b=null){const el=document.createElement('div');el.className='bubble'+(user?' user':'');el.textContent=text;if(b){const a=document.createElement('a');a.href=url('map.html',{bus:b.id});a.className='linkbutton';a.textContent=(lang==='ru'?'Посмотреть на карте →':'Картадан қарау →');el.append(document.createElement('br'),a)}$('#messages').append(el);$('#messages').scrollTop=$('#messages').scrollHeight}
 function ask(text){const q=text.trim();if(!q)return;message(q,true);const deadline=parseDeadline(q);let b;
  if(deadline!=null){const fits=BUSES.filter(x=>x.walk+x.eta<=deadline).sort((a,c)=>comfortScore(c)-comfortScore(a));b=fits[0]||BUSES.reduce((a,c)=>a.walk+a.eta<c.walk+c.eta?a:c);message(t().deadlineFit(deadline,b)+(fits.length?'':' '+t().deadlineMiss),false,b);$('#question').value='';return}
  const num=q.match(/\d+/);if(num)b=route(num[0]);else if(/свобод|мест|сид|загруз|бос орын/i.test(q))b=BUSES.reduce((a,c)=>a.seats>c.seats?a:c);else if(/быстр|раньше|приед|скоро|ерте|жылдам/i.test(q))b=BUSES.reduce((a,c)=>a.eta<c.eta?a:c);
  if(b)message(t().info(b),false,b);else message(t().fallback());$('#question').value=''}
 message(t().greet(CITIES[city].name));$('#chat-form').addEventListener('submit',e=>{e.preventDefault();ask($('#question').value)});document.querySelectorAll('[data-ask]').forEach(el=>el.addEventListener('click',()=>ask(el.dataset.ask)));
 document.querySelectorAll('[data-lang]').forEach(el=>el.addEventListener('click',()=>{save('lang',el.dataset.lang);assistant()}));
}
function renderFavorites(){const found=BUSES.filter(favored);$('#favorites').innerHTML=found.length?found.map(b=>busCard(b)).join(''):`<div class="card empty">${icon('heart')}<h3>Здесь будут любимые маршруты</h3><p>Нажми на звёздочку рядом с автобусом.</p><a class="secondary" href="${url('routes.html')}">Выбрать маршрут</a></div>`}
function renderRequests(){const list=requests.filter(r=>r.city===city);$('#requests').innerHTML=list.length?list.map(r=>`<article class="request-item"><strong>${esc(CITIES[city].stops[r.stop]||'Остановка')}</strong><p class="muted">${esc(new Date(r.time).toLocaleString('ru-RU',{day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'}))}</p><div class="actions"><span class="badge">На этом устройстве</span><button class="linkbutton" data-remove="${esc(r.id)}">Удалить</button></div></article>`).join(''):'<p class="muted">Будущих поездок пока нет.</p>'}
function trips(){
 $('#app').innerHTML=heading('Мои поездки','Избранное и планы в выбранном городе')+`<div class="twocol"><section><h2>Избранные маршруты</h2><div id="favorites"></div></section><section class="card"><h2>Мне нужен автобус</h2><p class="muted">Сохрани план поездки. Заявка хранится на этом устройстве и не отправляется перевозчику.</p><form id="request-form"><label class="field">Откуда поедешь?<select id="request-stop" required>${CITIES[city].stops.map((s,i)=>`<option value="${i}">${s}</option>`).join('')}</select></label><label class="field">Дата и время<input id="request-time" type="datetime-local" required></label><button class="primary full">Сохранить поездку ${icon('arrow')}</button></form><div class="section"><h2>Планы</h2><div id="requests"></div></div></section></div><p class="footnote">Сохранение действует в этом браузере. После очистки данных браузера записи исчезнут.</p>`;
 const input=$('#request-time');const localDate=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);input.min=localDate(new Date());input.value=localDate(new Date(Date.now()+3600000));
 $('#request-form').addEventListener('submit',e=>{e.preventDefault();const date=new Date(input.value);if(!Number.isFinite(date.getTime())||date.getTime()<=Date.now()){input.setCustomValidity('Выбери время в будущем.');input.reportValidity();return}input.setCustomValidity('');requests.push({id:Date.now().toString(36)+Math.random().toString(36).slice(2,6),city,stop:Number($('#request-stop').value),time:date.toISOString()});save('requests',requests);renderRequests();toast('Поездка сохранена на этом устройстве')});input.addEventListener('input',()=>input.setCustomValidity(''));document.addEventListener('click',e=>{const btn=e.target.closest('[data-remove]');if(!btn)return;requests=requests.filter(r=>r.id!==btn.dataset.remove);save('requests',requests);renderRequests();toast('Поездка удалена')});renderFavorites();renderRequests();
}
function settings(){
 $('#app').innerHTML=heading('Настройки')+`<section class="card"><h2>Тема оформления</h2><p class="muted">«Авто» следует теме устройства и меняется вместе с ней.</p><div class="filters" role="group" aria-label="Тема оформления"><button class="chip ${theme==='light'?'active':''}" data-theme-choice="light" aria-pressed="${theme==='light'}">${icon('sun')} Светлая</button><button class="chip ${theme==='dark'?'active':''}" data-theme-choice="dark" aria-pressed="${theme==='dark'}">${icon('moon')} Тёмная</button><button class="chip ${theme==='system'?'active':''}" data-theme-choice="system" aria-pressed="${theme==='system'}">${icon('gear')} Авто</button></div></section><section class="card section"><h2>Язык помощника</h2><p class="muted">На каком языке Aqyl отвечает по умолчанию в разделе «Помощник».</p><div class="filters" role="group" aria-label="Язык помощника"><button class="chip ${read('lang','ru')==='ru'?'active':''}" data-lang-choice="ru" aria-pressed="${read('lang','ru')==='ru'}">Русский</button><button class="chip ${read('lang','ru')==='kz'?'active':''}" data-lang-choice="kz" aria-pressed="${read('lang','ru')==='kz'}">Қазақша</button></div></section><section class="card section"><h2>Данные на этом устройстве</h2><p class="muted">Избранное (${favorites.length}) и заявки на поездку (${requests.filter(r=>r.city===city).length} в городе ${CITIES[city].name}) хранятся только в этом браузере — их не видит перевозчик.</p><button id="reset-data" class="secondary">${icon('heart')} Очистить избранное и заявки</button></section><p class="footnote">Настройки применяются сразу на всех страницах AqylJol и сохраняются локально на этом устройстве.</p>`;
 document.querySelectorAll('[data-theme-choice]').forEach(el=>el.addEventListener('click',()=>{theme=el.dataset.themeChoice;save('theme',theme);applyTheme(theme);document.querySelectorAll('[data-theme-choice]').forEach(x=>{x.classList.toggle('active',x===el);x.setAttribute('aria-pressed',String(x===el))});toast('Тема сохранена')}));
 document.querySelectorAll('[data-lang-choice]').forEach(el=>el.addEventListener('click',()=>{save('lang',el.dataset.langChoice);document.querySelectorAll('[data-lang-choice]').forEach(x=>{x.classList.toggle('active',x===el);x.setAttribute('aria-pressed',String(x===el))});toast('Язык помощника сохранён')}));
 $('#reset-data').addEventListener('click',()=>{favorites=[];requests=[];save('favorites',favorites);save('requests',requests);toast('Избранное и заявки очищены');settings()});
}
function about(){
 $('#app').innerHTML=heading('О нас','Команда AqylJol')+`<section class="about-hero"><div class="about-mark"><img src="assets/aqyljol-icon.svg" alt="Логотип AqylJol"></div><div><span class="eyebrow">СТУДЕНТЫ КОЛЛЕДЖА APEC</span><h2>Мы создаём город,<br>в котором легче быть в пути.</h2><p>Мы — студенты колледжа APEC и команда проекта AqylJol. Создали этот сервис, чтобы сделать поездки по городу понятнее: видеть маршруты, находить автобус и выбирать более комфортную поездку.</p></div></section><section class="about-benefits"><div class="benefits-intro"><span class="eyebrow">НАШЕ ОТЛИЧИЕ</span><h2>Почему AqylJol?</h2><p class="muted">Обычное транспортное приложение показывает, где находится автобус. AqylJol помогает решить, какой вариант лучше выбрать.</p></div><div class="benefits-list"><article><span>01</span><div><h3>Индекс комфорта</h3><p>Сравниваем ожидание, свободные места, пеший путь и пересадки в одной понятной оценке.</p></div></article><article><span>02</span><div><h3>Свободные места</h3><p>Показываем загруженность автобуса и предлагаем альтернативу, если маршрут почти заполнен.</p></div></article><article><span>03</span><div><h3>Умный помощник</h3><p>Можно написать «что приедет раньше?» или «как успеть к 8:00?» и получить конкретный вариант.</p></div></article><article><span>04</span><div><h3>Поездка от А до Б</h3><p>Выбираем остановки, учитываем пересадки и сразу открываем подходящий автобус на карте.</p></div></article></div></section><section class="about-compare"><div><span class="eyebrow">AQYLJOL / ПРОЕКТ СТУДЕНТОВ APEC</span><h2>Не только карта автобусов.</h2><p>Мы добавили человеческий слой: комфорт, понятные подсказки и собственный стиль. AqylJol создан для пассажира, который хочет быстрее принять решение и спокойно доехать.</p></div><div class="compare-pill"><span>Обычное приложение</span><b>Где автобус?</b><i>→</i><span>AqylJol</span><b>Как лучше доехать?</b></div></section><section class="about-grid"><article class="card about-card"><span class="about-number">05</span><h2>Наша идея</h2><p class="muted">AqylJol помогает быстро сориентироваться в маршрутах и не тратить лишнее время на ожидание. Мы объединили карту, маршруты, помощника и планы поездок в одном месте.</p></article><article class="card about-card"><span class="about-number">06</span><h2>Наша команда</h2><div class="team-list"><div><b>Серикболулы Ерсултан</b><small>Участник команды AqylJol</small></div><div><b>Артурулы Мирас</b><small>Участник команды AqylJol</small></div><div><b>Мубарак Ислам</b><small>Участник команды AqylJol</small></div></div></article></section><section class="card about-note"><span class="eyebrow">APEC COLLEGE · AQYLJOL</span><h2>Учимся. Создаём. Двигаемся вперёд.</h2><p class="muted">Проект создан студентами колледжа APEC как идея цифрового сервиса для города. Спасибо, что смотрите нашу работу.</p><a class="primary" href="${url('index.html')}">Вернуться на главную ${icon('arrow')}</a></section>`;
}
({home,map:mapPage,routes,assistant,trips,about,settings}[page]||home)();
// Optional browser tool: the same favorite action as the visible star button.
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'toggle_demo_favorite',description:'Toggle a demo bus favorite in the currently selected city on this device.',inputSchema:{type:'object',properties:{busId:{type:'string',enum:['14','30','12']}},required:['busId'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input.busId!=='string'||!route(input.busId))throw new Error('Unknown demo bus');toggleFavorite(input.busId);return {city,busId:input.busId,saved:favored(route(input.busId))}}})).catch(()=>{})}catch{}}
